//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_OC_Gerdau.Px_BodegaPT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.informat.cl", ConfigurationName="Px_BodegaPT.wsmovexiallSoapPort")]
    public interface wsmovexiallSoapPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (wsmovexiall.Execute) del mensaje ExecuteRequest no coincide con el valor predeterminado (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="www.informat.claction/AWSMOVEXIALL.Execute", ReplyAction="*")]
        Gestor_OC_Gerdau.Px_BodegaPT.ExecuteResponse Execute(Gestor_OC_Gerdau.Px_BodegaPT.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.informat.claction/AWSMOVEXIALL.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.Px_BodegaPT.ExecuteResponse> ExecuteAsync(Gestor_OC_Gerdau.Px_BodegaPT.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsmovexiall.Execute", WrapperNamespace="www.informat.cl", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.informat.cl", Order=0)]
        public string Intrasnporte;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Intrasnporte) {
            this.Intrasnporte = Intrasnporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsmovexiall.ExecuteResponse", WrapperNamespace="www.informat.cl", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.informat.cl", Order=0)]
        public string Outtansporte;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string Outtansporte) {
            this.Outtansporte = Outtansporte;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsmovexiallSoapPortChannel : Gestor_OC_Gerdau.Px_BodegaPT.wsmovexiallSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsmovexiallSoapPortClient : System.ServiceModel.ClientBase<Gestor_OC_Gerdau.Px_BodegaPT.wsmovexiallSoapPort>, Gestor_OC_Gerdau.Px_BodegaPT.wsmovexiallSoapPort {
        
        public wsmovexiallSoapPortClient() {
        }
        
        public wsmovexiallSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsmovexiallSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsmovexiallSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsmovexiallSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gestor_OC_Gerdau.Px_BodegaPT.ExecuteResponse Gestor_OC_Gerdau.Px_BodegaPT.wsmovexiallSoapPort.Execute(Gestor_OC_Gerdau.Px_BodegaPT.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(string Intrasnporte) {
            Gestor_OC_Gerdau.Px_BodegaPT.ExecuteRequest inValue = new Gestor_OC_Gerdau.Px_BodegaPT.ExecuteRequest();
            inValue.Intrasnporte = Intrasnporte;
            Gestor_OC_Gerdau.Px_BodegaPT.ExecuteResponse retVal = ((Gestor_OC_Gerdau.Px_BodegaPT.wsmovexiallSoapPort)(this)).Execute(inValue);
            return retVal.Outtansporte;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.Px_BodegaPT.ExecuteResponse> Gestor_OC_Gerdau.Px_BodegaPT.wsmovexiallSoapPort.ExecuteAsync(Gestor_OC_Gerdau.Px_BodegaPT.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.Px_BodegaPT.ExecuteResponse> ExecuteAsync(string Intrasnporte) {
            Gestor_OC_Gerdau.Px_BodegaPT.ExecuteRequest inValue = new Gestor_OC_Gerdau.Px_BodegaPT.ExecuteRequest();
            inValue.Intrasnporte = Intrasnporte;
            return ((Gestor_OC_Gerdau.Px_BodegaPT.wsmovexiallSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
