//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_OC_Gerdau.WS_ClientesWeb {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_ClientesWeb.WS_WebClientesSoap")]
    public interface WS_WebClientesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerObras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerObras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerObras", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerObrasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_WebClientesSoapChannel : Gestor_OC_Gerdau.WS_ClientesWeb.WS_WebClientesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_WebClientesSoapClient : System.ServiceModel.ClientBase<Gestor_OC_Gerdau.WS_ClientesWeb.WS_WebClientesSoap>, Gestor_OC_Gerdau.WS_ClientesWeb.WS_WebClientesSoap {
        
        public WS_WebClientesSoapClient() {
        }
        
        public WS_WebClientesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_WebClientesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_WebClientesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_WebClientesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerObras() {
            return base.Channel.ObtenerObras();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerObrasAsync() {
            return base.Channel.ObtenerObrasAsync();
        }
    }
}
