//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_OC_Gerdau.WsFacturacion {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ssingest.cl/TO/WS", ConfigurationName="WsFacturacion.FacturacionSoap")]
    public interface FacturacionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerDato", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ObtenerDato(string iTx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerDato", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ObtenerDatoAsync(string iTx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ListarParametro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ListarParametro(string where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ListarParametro", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ListarParametroAsync(string where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/GuardarCambioParametros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Gestor_OC_Gerdau.WsFacturacion.Parametro GuardarCambioParametros(string agencia, string usuario, int timer, int facturacionAutomatica, string motivo, string terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/GuardarCambioParametros", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.Parametro> GuardarCambioParametrosAsync(string agencia, string usuario, int timer, int facturacionAutomatica, string motivo, string terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ListarDespachoCamion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ListarDespachoCamion(string agencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ListarDespachoCamion", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ListarDespachoCamionAsync(string agencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/GuardarLogViaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Gestor_OC_Gerdau.WsFacturacion.Viaje GuardarLogViaje(string viaje, string agencia, string usuario, string estadoGuiaDespacho, string fechaGuiaDespacho, string respuestaGuiaDespacho, int nroINET, string estadoFacturacion, string fechaFacturacion, string respuestaFacturacion, string terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/GuardarLogViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.Viaje> GuardarLogViajeAsync(string viaje, string agencia, string usuario, string estadoGuiaDespacho, string fechaGuiaDespacho, string respuestaGuiaDespacho, int nroINET, string estadoFacturacion, string fechaFacturacion, string respuestaFacturacion, string terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerInformacionViaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Gestor_OC_Gerdau.WsFacturacion.Viaje ObtenerInformacionViaje(string viaje, string origen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerInformacionViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.Viaje> ObtenerInformacionViajeAsync(string viaje, string origen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ValidaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidaCliente(long iPor, string iClte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ValidaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ValidaClienteAsync(long iPor, string iClte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/PersitirDatosEvento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PersitirDatosEvento(string iEvento, string iObs, string iClte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/PersitirDatosEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PersitirDatosEventoAsync(string iEvento, string iObs, string iClte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerTotalDespachoSiguienteSemana_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long ObtenerTotalDespachoSiguienteSemana_V2(string iRut, string iTipo, int NroDias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerTotalDespachoSiguienteSemana_V2", ReplyAction="*")]
        System.Threading.Tasks.Task<long> ObtenerTotalDespachoSiguienteSemana_V2Async(string iRut, string iTipo, int NroDias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerDatosLN_Cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ObtenerDatosLN_Cliente(string iRut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerDatosLN_Cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ObtenerDatosLN_ClienteAsync(string iRut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerDatosLN_Cliente_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ObtenerDatosLN_Cliente_V2(string iRut, int iNroDias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/ObtenerDatosLN_Cliente_V2", ReplyAction="*")]
        System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ObtenerDatosLN_Cliente_V2Async(string iRut, int iNroDias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/NotificarEvento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool NotificarEvento(string iEvento, string iClte, long iPorcentaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/NotificarEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> NotificarEventoAsync(string iEvento, string iClte, long iPorcentaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/CambiaEstadoCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CambiaEstadoCliente(string iRut, bool lEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/CambiaEstadoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CambiaEstadoClienteAsync(string iRut, bool lEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/EnviaCorreoNotificacion_LC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EnviaCorreoNotificacion_LC(string iRut, string iTipoNot, string iListDest, string iRZ, string iTLC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/EnviaCorreoNotificacion_LC", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EnviaCorreoNotificacion_LCAsync(string iRut, string iTipoNot, string iListDest, string iRZ, string iTLC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/Obtener_LINEA_CREDITO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Obtener_LINEA_CREDITO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ssingest.cl/TO/WS/Obtener_LINEA_CREDITO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Obtener_LINEA_CREDITOAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ssingest.cl/TO/WS")]
    public partial class ListaDataSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet _dataSetField;
        
        private string _errorField;
        
        private System.Data.DataSet dataSetField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataSet _dataSet {
            get {
                return this._dataSetField;
            }
            set {
                this._dataSetField = value;
                this.RaisePropertyChanged("_dataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string _error {
            get {
                return this._errorField;
            }
            set {
                this._errorField = value;
                this.RaisePropertyChanged("_error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
                this.RaisePropertyChanged("DataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ssingest.cl/TO/WS")]
    public partial class Viaje : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string viaje1Field;
        
        private string estadoGuiaField;
        
        private string fechaGuiaField;
        
        private short nroINETField;
        
        private string estadoFacturaField;
        
        private string fechaFacturaField;
        
        private string respuestaGuiaField;
        
        private string respuestaFacturaField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Viaje", Order=0)]
        public string Viaje1 {
            get {
                return this.viaje1Field;
            }
            set {
                this.viaje1Field = value;
                this.RaisePropertyChanged("Viaje1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EstadoGuia {
            get {
                return this.estadoGuiaField;
            }
            set {
                this.estadoGuiaField = value;
                this.RaisePropertyChanged("EstadoGuia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FechaGuia {
            get {
                return this.fechaGuiaField;
            }
            set {
                this.fechaGuiaField = value;
                this.RaisePropertyChanged("FechaGuia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short NroINET {
            get {
                return this.nroINETField;
            }
            set {
                this.nroINETField = value;
                this.RaisePropertyChanged("NroINET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EstadoFactura {
            get {
                return this.estadoFacturaField;
            }
            set {
                this.estadoFacturaField = value;
                this.RaisePropertyChanged("EstadoFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FechaFactura {
            get {
                return this.fechaFacturaField;
            }
            set {
                this.fechaFacturaField = value;
                this.RaisePropertyChanged("FechaFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RespuestaGuia {
            get {
                return this.respuestaGuiaField;
            }
            set {
                this.respuestaGuiaField = value;
                this.RaisePropertyChanged("RespuestaGuia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RespuestaFactura {
            get {
                return this.respuestaFacturaField;
            }
            set {
                this.respuestaFacturaField = value;
                this.RaisePropertyChanged("RespuestaFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ssingest.cl/TO/WS")]
    public partial class Parametro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tablaField;
        
        private string codIntField;
        
        private string descripcionField;
        
        private string alf1Field;
        
        private string alf2Field;
        
        private string alf3Field;
        
        private int num1Field;
        
        private int num2Field;
        
        private int num3Field;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Tabla {
            get {
                return this.tablaField;
            }
            set {
                this.tablaField = value;
                this.RaisePropertyChanged("Tabla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("CodInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Alf1 {
            get {
                return this.alf1Field;
            }
            set {
                this.alf1Field = value;
                this.RaisePropertyChanged("Alf1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Alf2 {
            get {
                return this.alf2Field;
            }
            set {
                this.alf2Field = value;
                this.RaisePropertyChanged("Alf2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Alf3 {
            get {
                return this.alf3Field;
            }
            set {
                this.alf3Field = value;
                this.RaisePropertyChanged("Alf3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Num1 {
            get {
                return this.num1Field;
            }
            set {
                this.num1Field = value;
                this.RaisePropertyChanged("Num1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Num2 {
            get {
                return this.num2Field;
            }
            set {
                this.num2Field = value;
                this.RaisePropertyChanged("Num2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Num3 {
            get {
                return this.num3Field;
            }
            set {
                this.num3Field = value;
                this.RaisePropertyChanged("Num3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FacturacionSoapChannel : Gestor_OC_Gerdau.WsFacturacion.FacturacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturacionSoapClient : System.ServiceModel.ClientBase<Gestor_OC_Gerdau.WsFacturacion.FacturacionSoap>, Gestor_OC_Gerdau.WsFacturacion.FacturacionSoap {
        
        public FacturacionSoapClient() {
        }
        
        public FacturacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacturacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ObtenerDato(string iTx) {
            return base.Channel.ObtenerDato(iTx);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ObtenerDatoAsync(string iTx) {
            return base.Channel.ObtenerDatoAsync(iTx);
        }
        
        public Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ListarParametro(string where) {
            return base.Channel.ListarParametro(where);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ListarParametroAsync(string where) {
            return base.Channel.ListarParametroAsync(where);
        }
        
        public Gestor_OC_Gerdau.WsFacturacion.Parametro GuardarCambioParametros(string agencia, string usuario, int timer, int facturacionAutomatica, string motivo, string terminal) {
            return base.Channel.GuardarCambioParametros(agencia, usuario, timer, facturacionAutomatica, motivo, terminal);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.Parametro> GuardarCambioParametrosAsync(string agencia, string usuario, int timer, int facturacionAutomatica, string motivo, string terminal) {
            return base.Channel.GuardarCambioParametrosAsync(agencia, usuario, timer, facturacionAutomatica, motivo, terminal);
        }
        
        public Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ListarDespachoCamion(string agencia) {
            return base.Channel.ListarDespachoCamion(agencia);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ListarDespachoCamionAsync(string agencia) {
            return base.Channel.ListarDespachoCamionAsync(agencia);
        }
        
        public Gestor_OC_Gerdau.WsFacturacion.Viaje GuardarLogViaje(string viaje, string agencia, string usuario, string estadoGuiaDespacho, string fechaGuiaDespacho, string respuestaGuiaDespacho, int nroINET, string estadoFacturacion, string fechaFacturacion, string respuestaFacturacion, string terminal) {
            return base.Channel.GuardarLogViaje(viaje, agencia, usuario, estadoGuiaDespacho, fechaGuiaDespacho, respuestaGuiaDespacho, nroINET, estadoFacturacion, fechaFacturacion, respuestaFacturacion, terminal);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.Viaje> GuardarLogViajeAsync(string viaje, string agencia, string usuario, string estadoGuiaDespacho, string fechaGuiaDespacho, string respuestaGuiaDespacho, int nroINET, string estadoFacturacion, string fechaFacturacion, string respuestaFacturacion, string terminal) {
            return base.Channel.GuardarLogViajeAsync(viaje, agencia, usuario, estadoGuiaDespacho, fechaGuiaDespacho, respuestaGuiaDespacho, nroINET, estadoFacturacion, fechaFacturacion, respuestaFacturacion, terminal);
        }
        
        public Gestor_OC_Gerdau.WsFacturacion.Viaje ObtenerInformacionViaje(string viaje, string origen) {
            return base.Channel.ObtenerInformacionViaje(viaje, origen);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.Viaje> ObtenerInformacionViajeAsync(string viaje, string origen) {
            return base.Channel.ObtenerInformacionViajeAsync(viaje, origen);
        }
        
        public bool ValidaCliente(long iPor, string iClte) {
            return base.Channel.ValidaCliente(iPor, iClte);
        }
        
        public System.Threading.Tasks.Task<bool> ValidaClienteAsync(long iPor, string iClte) {
            return base.Channel.ValidaClienteAsync(iPor, iClte);
        }
        
        public string PersitirDatosEvento(string iEvento, string iObs, string iClte) {
            return base.Channel.PersitirDatosEvento(iEvento, iObs, iClte);
        }
        
        public System.Threading.Tasks.Task<string> PersitirDatosEventoAsync(string iEvento, string iObs, string iClte) {
            return base.Channel.PersitirDatosEventoAsync(iEvento, iObs, iClte);
        }
        
        public long ObtenerTotalDespachoSiguienteSemana_V2(string iRut, string iTipo, int NroDias) {
            return base.Channel.ObtenerTotalDespachoSiguienteSemana_V2(iRut, iTipo, NroDias);
        }
        
        public System.Threading.Tasks.Task<long> ObtenerTotalDespachoSiguienteSemana_V2Async(string iRut, string iTipo, int NroDias) {
            return base.Channel.ObtenerTotalDespachoSiguienteSemana_V2Async(iRut, iTipo, NroDias);
        }
        
        public Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ObtenerDatosLN_Cliente(string iRut) {
            return base.Channel.ObtenerDatosLN_Cliente(iRut);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ObtenerDatosLN_ClienteAsync(string iRut) {
            return base.Channel.ObtenerDatosLN_ClienteAsync(iRut);
        }
        
        public Gestor_OC_Gerdau.WsFacturacion.ListaDataSet ObtenerDatosLN_Cliente_V2(string iRut, int iNroDias) {
            return base.Channel.ObtenerDatosLN_Cliente_V2(iRut, iNroDias);
        }
        
        public System.Threading.Tasks.Task<Gestor_OC_Gerdau.WsFacturacion.ListaDataSet> ObtenerDatosLN_Cliente_V2Async(string iRut, int iNroDias) {
            return base.Channel.ObtenerDatosLN_Cliente_V2Async(iRut, iNroDias);
        }
        
        public bool NotificarEvento(string iEvento, string iClte, long iPorcentaje) {
            return base.Channel.NotificarEvento(iEvento, iClte, iPorcentaje);
        }
        
        public System.Threading.Tasks.Task<bool> NotificarEventoAsync(string iEvento, string iClte, long iPorcentaje) {
            return base.Channel.NotificarEventoAsync(iEvento, iClte, iPorcentaje);
        }
        
        public string CambiaEstadoCliente(string iRut, bool lEstado) {
            return base.Channel.CambiaEstadoCliente(iRut, lEstado);
        }
        
        public System.Threading.Tasks.Task<string> CambiaEstadoClienteAsync(string iRut, bool lEstado) {
            return base.Channel.CambiaEstadoClienteAsync(iRut, lEstado);
        }
        
        public string EnviaCorreoNotificacion_LC(string iRut, string iTipoNot, string iListDest, string iRZ, string iTLC) {
            return base.Channel.EnviaCorreoNotificacion_LC(iRut, iTipoNot, iListDest, iRZ, iTLC);
        }
        
        public System.Threading.Tasks.Task<string> EnviaCorreoNotificacion_LCAsync(string iRut, string iTipoNot, string iListDest, string iRZ, string iTLC) {
            return base.Channel.EnviaCorreoNotificacion_LCAsync(iRut, iTipoNot, iListDest, iRZ, iTLC);
        }
        
        public System.Data.DataSet Obtener_LINEA_CREDITO() {
            return base.Channel.Obtener_LINEA_CREDITO();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Obtener_LINEA_CREDITOAsync() {
            return base.Channel.Obtener_LINEA_CREDITOAsync();
        }
    }
}
